# This workflow will publish the master branch assets to production
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd TeamSuite.Web
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../web-publish -r linux-x64 --self-contained true    
    - name: Push
      uses: s0/git-publish-subdir-action@develop      
      env:
        REPO: self
        BRANCH: production # The branch name where you want to push the assets     
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message      
